export const URLS = {
  HOME: "/",
  CONTACT_US: "/contact-us",
  CAREERS: "/careers",
  ABOUT: "/about",
  BUY: "/buy",
  THANK_YOU: "/thank-you",
  SEARCH_RESULT: "/search-results",
  LETTER_OF_OFFER: "/letter-of-offer",
  PROPERTY: "/property/:id",
  SOLD_PROPERTIES: "/sold-properties",
  LEASE_PROPERTIES: "/leased-properties",
  LEASE: "/lease",
  PRIVACY_POLICY: "/privacy-policy",
  TERM_AND_CONDITION: "/terms-and-conditions",
  UPCOMING_AUCTIONS: "/upcoming-auction",
  UPCOMING_INSPECTIONS: "/upcoming-inspection",
  SELL_WITH_STALWART: "/sell-with-stalwart",
  SWITCH_TO_STALWART: "/switch-to-stalwart",
  INSTAGRAM: "https://www.instagram.com/stalwart_re/",
  FACEBOOK: "https://www.facebook.com/StalwartRE",
  CORELANDS: "https://corelands.com.au/",
  LINKED_IN:
    "https://www.linkedin.com/company/stalwart-real-estate/?lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BiDG%2BiyktQd%2BxMqCptTgCiA%3D%3D",
};
